#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Módulos
import pygame
import administrador
import menu_principal

def main():
    adm = administrador.Administrador()
    escena1 = menu_principal.Inicio(adm)
    adm.change_scene(escena1)
    adm.loop()

if __name__ == '__main__':
    pygame.init()
    main()
