#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Módulos

# Constantes
import escena


# Clases
# ---------------------------------------------------------------------

class Inicio(escena.Escena):
    """Escena inicial del juego, esta es la primera que se carga cuando inicia"""
    
    def __init__(self, administrador):
        escena.Escena.__init__(self, administrador)
       
    def on_update(self):
        pass

    def on_event(self):
        pass

    def on_draw(self, pantalla):
        pass
